import esbuild from "esbuild";
import process from "process";
import { readFileSync } from "node:fs";
import { builtinModules as builtins } from "node:module";
import { canonicalBuildInputDigest } from "./scripts/build-provenance.mjs";
import { mathWorkerPlugin } from "./scripts/math-worker.mjs";

const banner = `/*
Handwriting: pen ink on ordinary Markdown notes in Obsidian.
Generated by esbuild. The source lives in src/.
${readFileSync("THIRD_PARTY_NOTICES.md", "utf8")}
*/`;

const prod = process.argv[2] === "production";

// Keep the bundle byte-identical whether it is built from a checkout or from
// a source archive. The release receipt records the verified git commit/tree;
// the runtime retains a truthful, checkout-independent identity for the exact
// canonical build inputs, while git-only claims remain explicitly unverified.
const sourceCommit = "unverified";
const sourceTree = prod ? canonicalBuildInputDigest() : "unverified";
const dirtyStatus = "unverified";
const verified = false;

const ctx = await esbuild.context({
	plugins: [mathWorkerPlugin()],
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	define: {
		__HW_BUILD_SOURCE_COMMIT__: JSON.stringify(sourceCommit),
		__HW_BUILD_SOURCE_TREE__: JSON.stringify(sourceTree),
		__HW_BUILD_DIRTY_STATUS__: JSON.stringify(dirtyStatus),
		__HW_BUILD_VERIFIED__: JSON.stringify(verified),
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: process.env.HANDWRITING_BUILD_OUTFILE || "main.js",
	minify: prod,
});

if (prod) {
	await ctx.rebuild();
	process.exit(0);
} else {
	await ctx.watch();
}
